<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>io.github.luigidemasi</groupId>
        <artifactId>camel-kit</artifactId>
        <version>0.2.1-SNAPSHOT</version>
    </parent>

    <artifactId>camel-kit-main</artifactId>

    <name>Camel Kit :: Main</name>

    <properties>
        <dist.dir>dist</dist.dir>
    </properties>

    <dependencies>
        <dependency>
            <groupId>io.github.luigidemasi</groupId>
            <artifactId>camel-kit-core</artifactId>
            <version>${project.version}</version>
        </dependency>
    </dependencies>

    <build>
        <resources>
            <resource>
                <directory>src/main/jbang/main</directory>
                <targetPath>${basedir}/dist</targetPath>
                <includes>
                    <include>**/*.java</include>
                </includes>
            </resource>
        </resources>
        <sourceDirectory>src/main/jbang</sourceDirectory>
        <plugins>

            <plugin>
                <artifactId>maven-antrun-plugin</artifactId>
                <executions>
                    <execution>
                        <phase>prepare-package</phase>
                        <configuration>
                            <target>
                                <copy todir="${dist.dir}">
                                    <fileset dir="${project.build.directory}">
                                        <include name="**/*.java" />
                                    </fileset>
                                </copy>
                                <chmod file="${dist.dir}/*.java" perm="u+x" />
                            </target>
                        </configuration>
                        <goals>
                            <goal>run</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
        </plugins>
    </build>
</project>