# Camel-Kit Configuration
project:
  name: camel-kit
  camelVersion: "4.14.4.redhat-00008"
  citrusVersion: "4.9.2"

agent:
  name: claude
  folder: .claude/commands

catalog:
  source: bundled
  lastUpdated: 2026-03-31T16:31:21.216409450Z
