package io.github.luigidemasi.camelkit.graph.model;

public enum EdgeType {
    EXTENDS,
    IMPLEMENTS,
    DECLARES,
    CALLS,
    USES_TYPE,
    ROUTES_FROM,
    ROUTES_TO,
    PROCESSES,
    LINKS_TO,
    DEPENDS_ON,
    USES_COMPONENT,
    CONFIGURES,
    MULE_FLOW_CONTAINS,
    MULE_CALLS_SUBFLOW,
    MULE_USES_CONNECTOR,
    MULE_REFERENCES_DWL,
    BIZTALK_ORCHESTRATION_CONTAINS,
    BIZTALK_USES_MAP,
    BIZTALK_USES_SCHEMA,
    BIZTALK_CALLS_ORCHESTRATION,
    BIZTALK_PORT_BINDING,
    BIZTALK_FUNCTOID_CHAIN,
    BIZTALK_PIPELINE_STAGE
}
