package io.github.luigidemasi.camelkit.graph.model;

public enum NodeType {
    CLASS,
    METHOD,
    FIELD,
    CAMEL_ROUTE,
    CAMEL_ENDPOINT,
    CAMEL_PROCESSOR,
    MAVEN_ARTIFACT,
    CONFIG_PROPERTY,
    RESOURCE_FILE,
    MULE_FLOW,
    MULE_SUB_FLOW,
    MULE_CONNECTOR,
    MULE_ENDPOINT,
    MULE_PROCESSOR,
    MULE_TRANSFORM,
    MULE_ERROR_HANDLER,
    DATAWEAVE_SCRIPT
}
