package io.github.luigidemasi.camelkit.generator;

import java.nio.file.Files;
import java.nio.file.Path;

import io.github.luigidemasi.camelkit.config.AgentConfig;
import io.github.luigidemasi.camelkit.config.AgentRegistry;
import io.github.luigidemasi.camelkit.output.Printer;

import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.io.TempDir;

import static org.junit.jupiter.api.Assertions.*;

class ClaudeGeneratorTest {

    @TempDir
    Path tempDir;

    private InitContext createContext() {
        AgentConfig agent = AgentRegistry.get("claude");
        String agentBaseFolder = agent.folder().substring(0, agent.folder().lastIndexOf("/"));
        Path commandsDir = tempDir.resolve(agent.folder());
        Path skillsDir = tempDir.resolve(agentBaseFolder + "/skills");
        return new InitContext(
                agent, "claude", commandsDir, skillsDir, tempDir,
                "camel-kit", Printer.noop());
    }

    @Test
    void generatesClaudeMd() throws Exception {
        InitContext ctx = createContext();
        new ClaudeGenerator().generate(ctx);

        Path claudeMd = tempDir.resolve("CLAUDE.md");
        assertTrue(Files.exists(claudeMd));

        // Ultra-minimal AGENTS.md (generated by DefaultGenerator)
        Path agentsMd = tempDir.resolve("AGENTS.md");
        assertTrue(Files.exists(agentsMd));
        String agentsContent = Files.readString(agentsMd);
        assertTrue(agentsContent.contains("/camel-start"));
        assertTrue(agentsContent.contains("Laws"));
    }

    @Test
    void appendsParallelDispatchViaTrait() throws Exception {
        InitContext ctx = createContext();
        new ClaudeGenerator().generate(ctx);

        Path implementSkill = ctx.skillsDir().resolve("camel-implement/SKILL.md");
        assertTrue(Files.exists(implementSkill));
        String content = Files.readString(implementSkill);
        assertTrue(content.contains("Parallel Route Implementation"));
        assertTrue(content.contains("route-topology"));
        assertTrue(content.contains("<!-- TRAIT:claude -->"), "Should be applied via trait sentinel");
    }

    @org.junit.jupiter.params.ParameterizedTest
    @org.junit.jupiter.params.provider.ValueSource(strings = {"camel-kit", "camel kit"})
    void exposesShipThroughTheNativeRelaySkillAndReadOnlyWorker(String prefix) throws Exception {
        InitContext original = createContext();
        InitContext ctx = new InitContext(
                original.agent(), "claude", original.commandsDir(), original.skillsDir(),
                tempDir, prefix, Printer.noop());
        for (int initialization = 0; initialization < 2; initialization++) {
            new ClaudeGenerator().generate(ctx);
            String skill = Files.readString(tempDir.resolve(".claude/skills/camel-ship/SKILL.md"));
            assertTrue(skill.contains(prefix + " ship --backend claude-native --json"));
            assertTrue(skill.contains("subagent_type: \"camel-ship-worker\""));
            assertFalse(skill.contains("{COMMAND_PREFIX}"));
            assertFalse(skill.contains("<!-- TRAIT:claude -->"));
            String worker = Files.readString(tempDir.resolve(".claude/agents/camel-ship-worker.md"));
            assertTrue(worker.contains("name: camel-ship-worker"));
            assertTrue(worker.contains("tools: Read, Grep, Glob"));
            assertFalse(worker.contains("mcpServers"));
            String command = Files.readString(ctx.commandsDir().resolve("camel-ship.md"));
            assertTrue(command.contains("Read .claude/skills/camel-ship/SKILL.md and follow those instructions"));
            assertTrue(Files.readString(tempDir.resolve("CLAUDE.md")).contains("camel-ship-worker"));
        }
    }

    @Test
    void preservesBaseSkillBehavior() throws Exception {
        InitContext ctx = createContext();
        new ClaudeGenerator().generate(ctx);

        // Standard skills still have dispatch block
        Path brainstormSkill = ctx.skillsDir().resolve("camel-brainstorm/SKILL.md");
        assertTrue(Files.exists(brainstormSkill));
        String content = Files.readString(brainstormSkill);
        assertTrue(content.contains("Dispatch"));

        // Slash commands still exist
        assertTrue(Files.exists(ctx.commandsDir().resolve("camel-migrate.md")));
    }
}
