package io.github.luigidemasi.camelkit.generator;

import java.nio.file.Files;
import java.nio.file.Path;
import java.util.Set;
import java.util.regex.Pattern;
import java.util.stream.Collectors;

import io.github.luigidemasi.camelkit.config.AgentConfig;
import io.github.luigidemasi.camelkit.config.AgentDescriptor;
import io.github.luigidemasi.camelkit.config.AgentRegistry;
import io.github.luigidemasi.camelkit.output.Printer;

import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.ObjectMapper;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.io.TempDir;

import static org.junit.jupiter.api.Assertions.*;

class QwenGeneratorTest {

    @TempDir
    Path tempDir;

    private InitContext createContext() {
        AgentConfig agent = AgentRegistry.get("qwen");
        String agentBaseFolder = agent.folder().substring(0, agent.folder().lastIndexOf("/"));
        Path commandsDir = tempDir.resolve(agent.folder());
        Path skillsDir = tempDir.resolve(agentBaseFolder + "/skills");
        return new InitContext(
                agent, "qwen", commandsDir, skillsDir, tempDir,
                "camel-kit", Printer.noop());
    }

    @Test
    void generatesQwenMd() throws Exception {
        InitContext ctx = createContext();
        new QwenGenerator().generate(ctx);

        Path qwenMd = tempDir.resolve("QWEN.md");
        assertTrue(Files.exists(qwenMd));
        String content = Files.readString(qwenMd);
        assertTrue(content.contains("Workflow and Leaf Agents"));
        assertTrue(content.contains("primary session"));
        assertTrue(content.contains("read-only validation analysis"));
        assertFalse(content.contains("optional report writing"));

        // Ultra-minimal AGENTS.md (generated by DefaultGenerator)
        Path agentsMd = tempDir.resolve("AGENTS.md");
        assertTrue(Files.exists(agentsMd));
        String agentsContent = Files.readString(agentsMd);
        assertTrue(agentsContent.contains("/camel-start"));
        assertTrue(agentsContent.contains("Laws"));
        assertTrue(agentsContent.contains("config.properties"));
    }

    @Test
    void generatesSubAgents() throws Exception {
        InitContext ctx = createContext();
        new QwenGenerator().generate(ctx);

        Path agentsDir = tempDir.resolve(".qwen/agents");
        assertTrue(Files.isDirectory(agentsDir));
        assertTrue(Files.exists(agentsDir.resolve("camel-implementer.md")));
        assertTrue(Files.exists(agentsDir.resolve("camel-validator.md")));
        assertTrue(Files.exists(agentsDir.resolve("camel-tester.md")));
        try (var agents = Files.list(agentsDir)) {
            var files = agents.filter(Files::isRegularFile).toList();
            assertEquals(Set.of("camel-implementer.md", "camel-reviewer.md", "camel-validator.md", "camel-tester.md"),
                    files.stream().map(path -> path.getFileName().toString()).collect(Collectors.toSet()));
            for (Path agent : files) {
                String content = Files.readString(agent);
                assertFalse(content.contains("${project_name}"), agent.toString());
                assertFalse(content.contains("${current_directory}"), agent.toString());
            }
        }
    }

    @Test
    void removesRetiredOrchestratorAgentsOnRegeneration() throws Exception {
        InitContext ctx = createContext();
        Path agentsDir = tempDir.resolve(".qwen/agents");
        Files.createDirectories(agentsDir);
        for (String name : new String[]{
                "camel-brainstormer", "camel-planner", "camel-migrator", "camel-executor"}) {
            Files.writeString(agentsDir.resolve(name + ".md"), "stale generated profile");
        }

        new QwenGenerator().generate(ctx);

        for (String name : new String[]{
                "camel-brainstormer", "camel-planner", "camel-migrator", "camel-executor"}) {
            assertFalse(Files.exists(agentsDir.resolve(name + ".md")), name);
        }
    }

    @Test
    void generatesQwenIgnore() throws Exception {
        InitContext ctx = createContext();
        new QwenGenerator().generate(ctx);

        Path qwenIgnore = tempDir.resolve(".qwenignore");
        assertTrue(Files.exists(qwenIgnore));
        String content = Files.readString(qwenIgnore);
        assertTrue(content.contains("target/"));
    }

    @Test
    void primarySessionOwnsInteractiveWorkflows() throws Exception {
        InitContext ctx = createContext();
        new QwenGenerator().generate(ctx);

        String content = Files.readString(tempDir.resolve("QWEN.md"));
        assertTrue(content.contains("interviews, approvals, arguments, and phase handoffs"));
        assertFalse(Files.exists(tempDir.resolve(".qwen/agents/camel-brainstormer.md")));
        assertFalse(Files.exists(tempDir.resolve(".qwen/agents/camel-planner.md")));
        assertFalse(Files.exists(tempDir.resolve(".qwen/agents/camel-migrator.md")));
        assertFalse(Files.exists(tempDir.resolve(".qwen/agents/camel-executor.md")));
    }

    @Test
    void validatorIsReadOnlyAndReturnsItsRequiredReport() throws Exception {
        InitContext ctx = createContext();
        new QwenGenerator().generate(ctx);

        String content = Files.readString(
                tempDir.resolve(".qwen/agents/camel-validator.md"));
        assertTrue(content.contains("read_file"));
        assertTrue(content.contains("grep_search"));
        assertFalse(content.contains("write_file"));
        assertFalse(content.contains("\n  - edit"));
        assertTrue(content.contains("primary session writes the report"));
        assertTrue(content.contains("mcp__camel__camel_validate_route"));
        assertTrue(content.contains("mcp__camel__camel_route_harden_context"));
        assertTrue(content.contains("mcp__camel__camel_catalog_component_doc"));
        assertTrue(content.contains("mcp__camel__camel_configuration_validate"));
        assertTrue(content.contains("bounded validation analysis"));
        assertFalse(content.contains("follow those instructions exactly"));

    }

    @Test
    void leavesUseExplicitApprovalModeAndReviewerIsReadOnly() throws Exception {
        InitContext ctx = createContext();
        new QwenGenerator().generate(ctx);

        Path agentsDir = tempDir.resolve(".qwen/agents");
        for (String name : new String[]{"camel-implementer", "camel-reviewer", "camel-tester", "camel-validator"}) {
            assertTrue(Files.readString(agentsDir.resolve(name + ".md")).contains("approvalMode: default"), name);
        }
        String reviewer = Files.readString(agentsDir.resolve("camel-reviewer.md"));
        assertTrue(reviewer.contains("read_file"));
        assertFalse(reviewer.contains("write_file"));
        assertFalse(reviewer.contains("run_shell_command"));
        assertFalse(reviewer.contains("\n  - agent"));
    }

    @Test
    void installsAndReferencesCompletePersonaLibrary() throws Exception {
        InitContext ctx = createContext();
        new QwenGenerator().generate(ctx);

        Path personas = tempDir.resolve(".qwen/camel-kit-personas");
        assertDescriptorRegistersPersonas("qwen", ".qwen/camel-kit-personas");
        try (var files = Files.list(personas)) {
            assertEquals(Set.copyOf(PersonaResourceInstaller.PERSONAS),
                    files.map(path -> path.getFileName().toString().replace(".md", ""))
                            .collect(Collectors.toSet()));
        }
        String execute = Files.readString(ctx.skillsDir().resolve("camel-execute/SKILL.md"));
        assertTrue(execute.contains(".qwen/camel-kit-personas/catalog-researcher.md"));
        assertTrue(execute.contains(".qwen/camel-kit-personas/acr-moderator.md"));
        assertTrue(execute.contains(".qwen/camel-kit-personas/[persona].md"));
        assertFalse(execute.contains("`agents/"));
        assertNoBarePersonaReferences(ctx.skillsDir(), personas);
    }

    private void assertDescriptorRegistersPersonas(String agentName, String targetDirectory) {
        AgentDescriptor descriptor = AgentRegistry.descriptor(agentName);
        Set<String> targets = descriptor.templates().stream()
                .map(AgentDescriptor.TemplateInstall::target)
                .filter(target -> target.startsWith(targetDirectory + "/"))
                .map(target -> Path.of(target).getFileName().toString().replaceFirst("\\.md$", ""))
                .collect(Collectors.toSet());
        assertEquals(Set.copyOf(PersonaResourceInstaller.PERSONAS), targets);
    }

    @Test
    void testerSubAgentAllowsCamelAndCitrusMcpTools() throws Exception {
        InitContext ctx = createContext();
        new QwenGenerator().generate(ctx);

        String content = Files.readString(
                tempDir.resolve(".qwen/agents/camel-tester.md"));
        assertTrue(content.contains("mcp__camel__camel_validate_route"));
        assertTrue(content.contains("mcp__camel__camel_route_harden_context"));
        assertTrue(content.contains("mcp__camel__camel_component_properties"));
        assertTrue(content.contains("mcp__camel__camel_error_diagnose"));
        assertTrue(content.contains("mcp__citrus__citrus_catalog_actions"));
        assertTrue(content.contains("mcp__citrus__citrus_catalog_action_schema"));
        assertTrue(content.contains("mcp__citrus__citrus_catalog_endpoint_schema"));
        assertTrue(content.contains("mcp__citrus__citrus_docs_index"));
        assertFalse(content.contains("mcp_camel_"));
        assertFalse(content.contains("mcp_citrus_"));
    }

    @Test
    void implementationLeafInheritsToolsButCannotRedispatch() throws Exception {
        InitContext ctx = createContext();
        new QwenGenerator().generate(ctx);

        String implementer = Files.readString(
                tempDir.resolve(".qwen/agents/camel-implementer.md"));
        assertFalse(implementer.contains("\ntools:"));
        assertTrue(implementer.contains("disallowedTools:\n  - agent"));
    }

    @Test
    void keepsWorkflowCommandsInPrimarySessionAndForwardsArguments() throws Exception {
        InitContext ctx = createContext();
        new QwenGenerator().generate(ctx);

        for (String command : new String[]{
                "camel-brainstorm", "camel-plan", "camel-migrate", "camel-execute", "camel-validate"}) {
            String content = Files.readString(ctx.commandsDir().resolve(command + ".md"));
            assertTrue(content.contains("Read .qwen/skills"), command);
            assertTrue(content.contains("Requested input: {{args}}"), command);
            assertFalse(content.contains("agent tool with subagent_type"), command);
        }
    }

    @Test
    void generatedTraitsUseCurrentAgentAndForkSemantics() throws Exception {
        InitContext ctx = createContext();
        new QwenGenerator().generate(ctx);

        String brainstorm = Files.readString(ctx.skillsDir().resolve("camel-brainstorm/SKILL.md"));
        String execute = Files.readString(ctx.skillsDir().resolve("camel-execute/SKILL.md"));
        String plan = Files.readString(ctx.skillsDir().resolve("camel-plan/SKILL.md"));

        for (String skill : new String[]{brainstorm, execute}) {
            assertTrue(skill.contains("agent("));
            assertTrue(skill.contains("subagent_type=\"fork\""));
            assertTrue(skill.contains("run_in_background=true"));
            assertTrue(skill.contains("cannot dispatch any") && skill.contains("subagent"));
            assertFalse(skill.contains("Agent({"));
            assertFalse(skill.contains("No subagent_type"));
            assertFalse(skill.contains("`task` tool"));
        }
        assertTrue(brainstorm.contains("Omitting `subagent_type` launches\n"
                                       + "the regular general-purpose agent; it does not create a fork"));
        assertTrue(execute.contains("subagent_type=\"camel-reviewer\""));
        assertTrue(execute.contains("subagent_type=\"camel-implementer\""));
        assertTrue(execute.contains("subagent_type=\"camel-tester\""));
        assertFalse(execute.contains("camel-implementer or camel-tester"));
        assertTrue(execute.contains("`test-engineer` -> `camel-tester`"));
        assertTrue(execute.contains("including `migration-specialist` -> `camel-implementer`"));
        assertTrue(execute.contains("full selected persona from `.qwen/camel-kit-personas/`"));
        assertTrue(execute.contains("run_in_background=false"));
        assertTrue(execute.contains("one foreground `camel-reviewer` call per selected critic lane"));
        assertFalse(execute.contains("call `camel-validator` in the foreground for read-only spec compliance"));
        assertTrue(execute.contains("Do not ask a fork or critic to spawn the next phase"));
        assertTrue(execute.contains("run the internal\n`camel-verify` skill directly in the primary executor session"));
        assertTrue(execute.contains("Do not delegate verification"));
        assertTrue(plan.contains("one `agent` call per independent task in the same plan-analyzer wave"));
        assertTrue(plan.contains("run `/approval-mode default`"));
        assertFalse(plan.contains("Qwen executes tasks serially"));
        assertTrue(brainstorm.contains("primary\nsession owns interview decisions"));
    }

    @Test
    void preservesBaseSkillBehavior() throws Exception {
        InitContext ctx = createContext();
        new QwenGenerator().generate(ctx);

        // Standard commands without sub-agents keep default content
        String content = Files.readString(
                ctx.commandsDir().resolve("camel-knowledge.md"));
        assertTrue(content.contains("Read .qwen/skills"));

        JsonNode servers = new ObjectMapper().readTree(
                Files.readString(tempDir.resolve(".qwen/settings.json"))).path("mcpServers");
        for (String server : new String[]{"camel", "camel-knowledge", "citrus"}) {
            assertTrue(servers.path(server).path("includeTools").isArray());
            assertFalse(servers.path(server).has("autoApprove"));
            assertFalse(servers.path(server).has("alwaysAllow"));
            assertFalse(servers.path(server).has("trust"));
        }

        String publicSkill = Files.readString(ctx.skillsDir().resolve("camel-start/SKILL.md"));
        String internalSkill = Files.readString(ctx.skillsDir().resolve("camel-verify/SKILL.md"));
        assertTrue(publicSkill.contains("user-invocable: true"));
        assertTrue(internalSkill.contains("user-invocable: false"));
        String knowledge = Files.readString(ctx.skillsDir().resolve("camel-knowledge/SKILL.md"));
        assertTrue(knowledge.contains("dispatch it to\n`camel-reviewer`"));
        assertTrue(knowledge.contains(".qwen/camel-kit-personas/knowledge-researcher.md"));
        assertFalse(knowledge.contains("as a `knowledge-researcher` subagent"));
    }

    private void assertNoBarePersonaReferences(Path... roots) throws Exception {
        Pattern bareReference = Pattern.compile("(?<![A-Za-z0-9._/-])agents/");
        for (Path root : roots) {
            try (var files = Files.walk(root)) {
                for (Path file : files.filter(Files::isRegularFile)
                        .filter(path -> path.toString().endsWith(".md")).toList()) {
                    assertFalse(bareReference.matcher(Files.readString(file)).find(), file.toString());
                }
            }
        }
    }
}
