knowledge.mcp.version=${camel-kit-knowledge-version}
camel.mcp.version=${camel.mcp.version}
camel.mcp.repos=redhat=https://maven.repository.redhat.com/ga/,apache_snap=https://repository.apache.org/snapshots
knowledge.mcp.repos=redhat=https://maven.repository.redhat.com/ga/
camel.catalog.repos=https://maven.repository.redhat.com/ga/
