package io.github.luigidemasi.camelkit.generator;

import java.nio.file.Files;
import java.nio.file.Path;
import java.util.HashMap;
import java.util.Map;

import io.github.luigidemasi.camelkit.util.AnsiColors;

public class OpenCodeGenerator extends DefaultGenerator {

    private static final String[] AGENTS = {
            "brainstormer", "planner", "implementer",
            "validator", "tester", "migrator", "executor",
            "researcher", "reviewer"
    };

    private static final String EXECUTE_COMMAND = """
            ---
            description: Execute a ready Camel-Kit implementation plan
            agent: executor
            subtask: false
            ---

            Execute the implementation plan for this project. Requested pipeline or plan: %s
            """;

    private final QuteTemplateEngine templateEngine = new QuteTemplateEngine();
    private final PersonaResourceInstaller personaInstaller = new PersonaResourceInstaller();

    @Override
    public void generate(InitContext ctx) throws Exception {
        // Run default generation (commands, skills, MCP config)
        super.generate(ctx);

        Map<String, Object> data = new HashMap<>(
                Map.of(
                        "COMMAND_PREFIX", ctx.commandPrefix()));
        // AGENTS.md already generated by the shared generator flow.

        // OpenCode-specific: generate agent definitions
        generateAgents(ctx);
        personaInstaller.install(ctx, ".opencode/camel-kit-personas");

        // OpenCode-specific: select the primary executor without losing command arguments.
        generateExecuteCommand(ctx);
    }

    private void generateAgents(InitContext ctx) throws Exception {
        Path agentsDir = ctx.projectDir().resolve(".opencode/agents");
        Files.createDirectories(agentsDir);

        for (String agentName : AGENTS) {
            copyTemplateResource(
                    "templates/opencode/agents/" + agentName + ".md",
                    agentsDir.resolve(agentName + ".md"));
        }

        ctx.printer().println(AnsiColors.green("✓") + " Generated " + AGENTS.length + " OpenCode agent definitions");
    }

    private void generateExecuteCommand(InitContext ctx) throws Exception {
        String filename = "camel-execute." + ctx.agent().fileFormat();
        Files.writeString(
                ctx.commandsDir().resolve(filename),
                EXECUTE_COMMAND.replace("%s", ctx.agent().argPlaceholder()));
    }
}
