<?xml version="1.0" encoding="utf-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:b="http://schemas.microsoft.com/BizTalk/2003"
           targetNamespace="http://MyApp.Schemas.OrderSchema" xmlns:ns0="http://MyApp.Schemas.OrderSchema"
           elementFormDefault="qualified">
  <xs:element name="OrderSchema">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="OrderId" type="xs:string" />
        <xs:element name="OrderType" type="xs:string" />
        <xs:element name="FirstName" type="xs:string" />
        <xs:element name="LastName" type="xs:string" />
        <xs:element name="OrderDate" type="xs:string" />
        <xs:element name="Quantity" type="xs:int" />
        <xs:element name="UnitPrice" type="xs:decimal" />
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>
